SUBDIR=gpu_BetweennessCentr  \
	   gpu_BFS  \
	   gpu_ConnectedComp  \
	   gpu_DegreeCentr  \
	   gpu_GraphColoring  \
	   gpu_kCore  \
	   gpu_SSSP  \
	   gpu_TriangleCount

ROOT=../

include ${ROOT}/gen.mk

